# LAB-01:PYTHON  FUNCTIONS AND NUMPY


Name:Pavithra S
Roll No:225229125

### Part-I: Write a method for sigmoid function

In [42]:
import math

def mysigmoid(x):
    return 1 / (1 + math.exp(-x))

In [3]:
result = mysigmoid(4)
print(result)  


0.9820137900379085


In [4]:
import math

def mysigmoid(x):
    return 1 / (1 + math.exp(-x))

x = [1, 2, 3]
sigmoid_values = [mysigmoid(val) for val in x]

print(sigmoid_values)


[0.7310585786300049, 0.8807970779778823, 0.9525741268224334]


In [8]:
import numpy as np

def mysigmoid(x):
    return 1 / (1 + np.exp(-x))
x = [1, 2, 3]
sigmoid_values = [mysigmoid(val) for val in x]

print(sigmoid_values)


[0.7310585786300049, 0.8807970779778823, 0.9525741268224334]


In [7]:
result = mysigmoid(9)
print(result)  

0.9998766054240137


### Part-II: Gradient or derivative of sigmoid function

In [13]:
import numpy as np

def mysigmoidd(x):
    return 1 / (1 + np.exp(-x))

def sig_derivative(s):
    return s * (1 - s)


In [15]:
sig_derivative(6)

-30

In [14]:
mysigmoidd(6)

0.9975273768433653

In [11]:
import numpy as np

x = np.array([1, 2, 3])
s = mysigmoid(x)
gradient = sig_derivative(s)

print(gradient)


[0.19661193 0.10499359 0.04517666]


### Part-III: Write a method image_to_vector()

In [16]:
import numpy as np

def image_to_vector(image):
    length, height, _ = image.shape
    return image.reshape((length * height * 3, 1))


In [17]:
import numpy as np

image = np.random.randint(0, 255, size=(2, 3, 3))
vector = image_to_vector(image)

print(vector)


[[129]
 [ 20]
 [137]
 [178]
 [  1]
 [171]
 [ 45]
 [172]
 [ 97]
 [228]
 [158]
 [127]
 [ 11]
 [ 84]
 [ 33]
 [ 43]
 [ 77]
 [206]]


In [18]:
import numpy as np

def image_to_vector(image):
    length, height, _ = image.shape
    return image.reshape((length * height * 3, 1))

# Create a 3x3x3 array of RGB color values
image = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],
    [[255, 255, 0], [255, 0, 255], [0, 255, 255]],
    [[128, 128, 128], [64, 64, 64], [0, 0, 0]]
])

# Reshape the image array into a vector
vector = image_to_vector(image)

print(vector)


[[255]
 [  0]
 [  0]
 [  0]
 [255]
 [  0]
 [  0]
 [  0]
 [255]
 [255]
 [255]
 [  0]
 [255]
 [  0]
 [255]
 [  0]
 [255]
 [255]
 [128]
 [128]
 [128]
 [ 64]
 [ 64]
 [ 64]
 [  0]
 [  0]
 [  0]]


### Part-III: Write a method image_to_vector()

In [21]:
import numpy as np

def normalizeRows(x):
    norms = np.linalg.norm(x, axis=1, keepdims=True)
    return x / norms


In [22]:
import numpy as np

x = np.array([[0,3,4], [2,6, 4]])
normalized_x = normalizeRows(x)

print(normalized_x)


[[0.         0.6        0.8       ]
 [0.26726124 0.80178373 0.53452248]]


In [24]:
import numpy as np

x1 = np.array([9, 2, 5])
x2 = np.array([7, 2, 2])

multiplication = np.multiply(x1, x2)
dot_product = np.dot(x1, x2)

print("Multiplication:", multiplication)
print("Dot product:", dot_product)


Multiplication: [63  4 10]
Dot product: 77


In [25]:
import numpy as np

x1 = np.array([9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0, 4, 5, 7])
x2 = np.array([7, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0, 8, 5, 3])

multiplication = np.multiply(x1, x2)
dot_product = np.dot(x1, x2)

print("Multiplication:", multiplication)
print("Dot product:", dot_product)


Multiplication: [63  4 10  0  0 63 10  0  0  0 81  4 25  0  0 32 25 21]
Dot product: 338


In [26]:
import numpy as np
import time

# Set the size of the vectors
N = 1000000

# Generate random vectors of size N
vector1 = np.random.random(N)
vector2 = np.random.random(N)

# Perform multiplication operation
start_time = time.time()
multiplication_result = vector1 * vector2
end_time = time.time()
multiplication_time = end_time - start_time

# Perform vectorization operation
start_time = time.time()
vectorization_result = np.multiply(vector1, vector2)
end_time = time.time()
vectorization_time = end_time - start_time

# Print the running times
print("Multiplication Time:", multiplication_time)
print("Vectorization Time:", vectorization_time)


Multiplication Time: 0.004580497741699219
Vectorization Time: 0.0035119056701660156


### Part-VI: Implement L1 and L2 loss functions

In [31]:
import numpy as np

def loss_l1(y, ypred):
    return np.sum(np.abs(y - ypred))

# Test the function with given vectors
y = np.array([1, 0, 0, 1, 1])
ypred = np.array([0.9, 0.2, 0.1, 0.4, 0.9])

l1_loss = loss_l1(y, ypred)
print("L1 Loss:", l1_loss)


L1 Loss: 1.1


In [41]:
import numpy as np

def loss_l2(y, ypred):
    return np.mean((y - ypred) /2 )

# Test the function with given vectors
y = np.array([1, 0, 0, 1, 1])
ypred = np.array([0.9, 0.2, 0.1, 0.4, 0.9])

l2_loss = loss_l2(y, ypred)
print("L2 Loss:", l2_loss)


L2 Loss: 0.04999999999999999
